# Generated by Django 5.2.7 on 2026-01-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_shipping_address_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_expiry_month',
            field=models.CharField(blank=True, help_text='Expiry month (MM)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_expiry_year',
            field=models.CharField(blank=True, help_text='Expiry year (YYYY)', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_holder_name',
            field=models.CharField(blank=True, help_text='Cardholder name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits for display', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted credit card number', null=True),
        ),
        # Note: is_paid, paid_at, payment_method, and purchase_price already exist in the database
        # They were added in previous migrations that were already applied
    ]
