# Generated by Django 5.2.7 on 2026-01-12 21:36

from django.db import migrations, models


def add_fields_if_not_exists(apps, schema_editor):
    """
    Add fields only if they don't already exist in the database.
    This handles cases where the database state is ahead of migrations.
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check which columns exist
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='orders_order'
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}
        
        # Add is_paid if it doesn't exist
        if 'is_paid' not in existing_columns:
            cursor.execute("ALTER TABLE orders_order ADD COLUMN is_paid BOOLEAN DEFAULT FALSE")
        
        # Add paid_at if it doesn't exist
        if 'paid_at' not in existing_columns:
            cursor.execute("ALTER TABLE orders_order ADD COLUMN paid_at TIMESTAMP NULL")
        
        # Add payment_method if it doesn't exist
        if 'payment_method' not in existing_columns:
            cursor.execute("""
                ALTER TABLE orders_order 
                ADD COLUMN payment_method VARCHAR(20) DEFAULT 'pending'
            """)
        
        # Add shipping_fee if it doesn't exist
        if 'shipping_fee' not in existing_columns:
            cursor.execute("""
                ALTER TABLE orders_order 
                ADD COLUMN shipping_fee NUMERIC(10, 2) DEFAULT 0
            """)
        
        # Check OrderItem columns
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='orders_orderitem'
        """)
        existing_item_columns = {row[0] for row in cursor.fetchall()}
        
        # Add purchase_price if it doesn't exist
        if 'purchase_price' not in existing_item_columns:
            cursor.execute("""
                ALTER TABLE orders_orderitem 
                ADD COLUMN purchase_price NUMERIC(10, 2) NULL
            """)


def reverse_migration(apps, schema_editor):
    """Reverse migration - remove fields if they exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check which columns exist before removing
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='orders_order'
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}
        
        if 'shipping_fee' in existing_columns:
            cursor.execute("ALTER TABLE orders_order DROP COLUMN shipping_fee")
        if 'payment_method' in existing_columns:
            cursor.execute("ALTER TABLE orders_order DROP COLUMN payment_method")
        if 'paid_at' in existing_columns:
            cursor.execute("ALTER TABLE orders_order DROP COLUMN paid_at")
        if 'is_paid' in existing_columns:
            cursor.execute("ALTER TABLE orders_order DROP COLUMN is_paid")
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='orders_orderitem'
        """)
        existing_item_columns = {row[0] for row in cursor.fetchall()}
        
        if 'purchase_price' in existing_item_columns:
            cursor.execute("ALTER TABLE orders_orderitem DROP COLUMN purchase_price")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_card_expiry_month_order_card_expiry_year_and_more'),
    ]

    operations = [
        migrations.RunPython(add_fields_if_not_exists, reverse_migration),
    ]
