# Generated by Django 5.2.7 on 2025-11-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('warranty', models.IntegerField(default=0, help_text='Guarentee time (month)')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
