# Generated by Django 5.2.7 on 2025-12-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('phones', 'Phones'), ('laptops', 'Laptops & Ultrabooks'), ('tablets', 'Tablets & E-Readers'), ('desktops', 'Desktops & All-in-Ones'), ('monitors', 'Monitors'), ('components', 'PC Components'), ('peripherals', 'Keyboards, Mice & Input'), ('networking', 'Networking & Modems'), ('audio', 'Headphones & Speakers'), ('tv_video', 'TV & Video'), ('gaming', 'Gaming Consoles & Accessories'), ('smart_home', 'Smart Home'), ('wearables', 'Wearables'), ('storage', 'External Storage & SSD/HDD'), ('printers', 'Printers & Scanners'), ('accessories', 'Cables & Accessories'), ('drones', 'Drones'), ('photo_video', 'Cameras & Photo')], help_text='Main category of the product (e.g. phones, laptops, audio)', max_length=50, null=True),
        ),
    ]
