# Generated by Django 5.2.7 on 2025-12-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('phones', 'Phones'), ('laptops', 'Laptops & Ultrabooks'), ('tablets', 'Tablets & E-Readers'), ('desktops', 'Desktops & All-in-Ones'), ('monitors', 'Monitors'), ('components', 'PC Components'), ('peripherals', 'Keyboards, Mice & Input'), ('networking', 'Networking & Modems'), ('audio', 'Headphones & Speakers'), ('tv_video', 'TV & Video'), ('gaming', 'Gaming Consoles & Accessories'), ('smart_home', 'Smart Home'), ('wearables', 'Wearables'), ('storage', 'External Storage & SSD/HDD'), ('printers', 'Printers & Scanners'), ('accessories', 'Cables & Accessories'), ('drones', 'Drones'), ('photo_video', 'Cameras & Photo')], db_index=True, help_text='Main category of the product (e.g. phones, laptops, audio)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='products_pr_stock_4d23d5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
    ]
