# Generated by Django 5.2.7 on 2025-12-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
        ('products', '0003_alter_product_category_and_more'),
    ]

    operations = [
    ]
