# Generated by Django 5.2.7 on 2026-01-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_discount_percentage_product_is_on_sale'),
        ('products', '0008_populate_categories'),
    ]

    operations = [
    ]
