# Generated by Django 5.2.7 on 2026-01-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_merge_20260113_1359'),
        ('products', '0009_product_original_price'),
    ]

    operations = [
    ]
