# Generated by Django 5.2.7 on 2025-12-11 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category_and_more'),
        ('reviews', '0002_rename_comments_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['product', 'status'], name='reviews_com_product_12bf5c_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['status', '-created_at'], name='reviews_com_status_f55ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['product'], name='reviews_rat_product_62fa76_idx'),
        ),
    ]
