# Generated by Django 5.2.7 on 2025-12-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='taxID',
        ),
    ]
