# Generated by Django 5.2.7 on 2025-12-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customer_home_address_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Product Manager', 'Product Manager'), ('Sales Manager', 'Sales Manager')], default='Customer', max_length=20),
        ),
    ]
