# Generated by Django 5.2.7 on 2026-01-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Product Manager', 'Product Manager'), ('Sales Manager', 'Sales Manager'), ('Support Agent', 'Support Agent')], default='Customer', max_length=50),
        ),
    ]
